### ISSUE TITLE
What is the meaning of ExposureTimes and ExposureBias in the dataset? 

### ISSUE THREAD

**Issue by Taichi-Pink** [rajat95/Deep-Deghosting-HDR#3]
I want to use this dataset to train my model; I am confused about the meanings of ExposureTimes and ExposureBias in the dataset. Thanks for your reply!

**Comment by KRamPrabhakar** [comment]
Hi,

The exact exposure times of the images are given in the ExposureTimes.txt file. Whereas the exposure bias with respect to the first image is provided in ExposureBias.txt file. The least exposure image's bias is set to EV 0 and the consecutive image I's bias is computed by log2(exp_time_of_image_I/exp_time_of_image_0). The exposure time information is provided since some non-deep methods require exposure time for their algorithm.
